using System.Collections.Immutable;
using System.Numerics;

namespace DesktopLizard.Core;

/// <summary>
/// Immutable behavior data captured after a simulation frame. The debug
/// renderer consumes this instead of reading a controller while it is being
/// advanced through fixed substeps.
/// </summary>
internal readonly record struct BehaviorDebugSnapshot(
    RoamingState State,
    StateTransitionReason LastTransitionReason,
    int TransitionSerial,
    Vector2 Position,
    Vector2 Target,
    Vector2 LookTarget,
    float Heading,
    float Speed,
    float DesiredSpeed,
    float NormalizedSpeed,
    float TurnVelocity,
    float DesiredTurnVelocity,
    float LookAngleOffset,
    float LookAngleTarget,
    float EmotionTimeRemaining,
    float StateTimeRemaining,
    float BoutTimeRemaining,
    float TurnRemaining,
    float TurnDirection,
    bool RestPending,
    bool ForwardExtended,
    bool IsPaused,
    EmotionBlend Emotion,
    float DropProgress,
    LostGripFallPhase LostGripPhase,
    float LostGripFallProgress,
    float LostGripReachProgress,
    float LostGripRegripProgress,
    float LostGripVerticalVelocity,
    float LostGripDistance,
    float LostGripTargetDistance,
    float SCurveElapsed,
    float SCurveDuration,
    float SCurveCycleDuration,
    int SCurveCycleCount,
    float SCurveProgress,
    float SCurveEasedProgress,
    float SCurveAmplitude,
    float SCurveDirection,
    float MouseAttentionTime,
    float MouseLostTime,
    float MouseCooldown,
    bool MouseNeedsLeave,
    bool HasMouseTarget,
    Vector2 MouseTarget,
    float SprintDistance,
    float SprintTargetDistance,
    float SprintMinimumTime,
    float MotionWatchdog,
    float ForwardLookAhead,
    float MinimumEdgeClearance,
    float PositiveSideClearance,
    float NegativeSideClearance);

internal readonly record struct LegDebugSnapshot(
    int Index,
    int Pair,
    int Side,
    int BodyIndex,
    bool IsFront,
    Vector2 Shoulder,
    Vector2 Elbow,
    Vector2 Foot,
    Vector2 StepFrom,
    Vector2 StepTo,
    Vector2 StepNormal,
    bool IsStepping,
    bool IsSwingMoving,
    float StepProgress,
    float StepDelayRemaining,
    float Lift,
    float StepDuration,
    float StepSpan,
    float StepHeight,
    float MaximumReach,
    float LastReachCorrection,
    float MaximumKinematicCorrection,
    int StepSerial,
    int ReachProjectionSerial,
    int StepTargetClampSerial,
    int SwingClampSerial);

/// <summary>
/// Immutable pose and gait data. Arrays are copied only while the debug layer
/// is enabled, so normal desktop-pet rendering keeps its allocation profile.
/// </summary>
internal sealed record LizardDebugSnapshot(
    ImmutableArray<Vector2> SpineJoints,
    ImmutableArray<float> SpineAngles,
    ImmutableArray<LegDebugSnapshot> Legs,
    float Heading,
    float BlinkAmount,
    float BodyBob,
    float TailSwayOffset,
    float BodyWidthScale,
    int NextPair,
    float SupportTimeRemaining,
    float AllFeetDownAge,
    float StepWaitTime,
    float PairError0,
    float PairError1,
    float LastGaitDisplaySpeed,
    bool DanglingActive,
    float DanglingGrabError,
    float DanglingConstraintError,
    float DanglingSpineError,
    float DanglingUpperLegError,
    float DanglingLowerLegError);
